### ISSUE TITLE
Manually modifying SentencePiece model?

### ISSUE THREAD

**Issue by neubig** [google/sentencepiece#121]
Hello,

I'd like to try to take in an existing sentencepiece model, modify some of its probabilities manually, then  use it to segment text. What would be the easiest way to do this? The ".vocab" file is easy to modify, but the ".model" file is binary format, and it wasn't clear what to do here.

**Comment by taku910** [comment]
The model file is just a serialized Protocol buffer. The  proto definition can be found [here](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L193).

Here's the python code to modify the score and store the model as 'new.model'.

```
% cd src
% protoc --python_out=. sentencepiece_model.proto
```

```
>>> import sentencepiece_model_pb2 as model
>>> m = model.ModelProto()
>>> m.ParseFromString(open('../python/test/test_ja_model.model', 'rb').read())
352301
>>> for p in m.pieces:
...     p.score += 10.0
... 
>>> with open('new.model', 'wb') as f:
...     f.write(m.SerializeToString())
```

```
% spm_export_vocab --model=new.model --output_format=proto | less
```

**Comment by taku910** [comment]
FYI:

I've recently added a new API to initialize the processor from serialized model. 
```
sp = spm.SentencePieceProcessor()
sp.LoadFromSerializedString(m.SerializedToString())
```

**Comment by neubig** [comment]
Great, thanks so much for the quick response!

**Comment by cindyxinyiwang** [comment]
Hi! I am wondering what is this python module: `import sentencepiece_model_pb2 as model` .  Is it another proto buff library that I have to download myself?

**Comment by taku910** [comment]
sentencepiece_model_pb2.py is machine generated py module.  You can generate it with protoc compiler.

```
% git clone https://github.com/google/sentencepiece.git
% cd sentencepiece/src
% protoc --python_out=. sentencepiece_model.proto
% ls *.py
sentencepiece_model_pb2.py

```
For more detail, please see 
https://developers.google.com/protocol-buffers/docs/pythontutorial

**Comment by cindyxinyiwang** [comment]
Thanks a lot. It is very helpful!

**Comment by liuxuanye888** [comment]
How to add new vocabulary to the generated model file

**Comment by rewicks** [comment]
Hi! I am trying to create a multilingual bpe vocabulary by unioning vocabularies trained on the individual languages. I am using this technique instead of upsampling during training to have more control over language balance in the end vocab.

I have used the above and https://github.com/google/sentencepiece/blob/master/python/add_new_vocab.ipynb to create a new model but the model is unable to be loaded by either the python module or CLI.

I get a vague error of:

```spm_encode_main.cc(52) [_status.ok()] Internal: /home/conda/feedstock_root/build_artifacts/sentencepiece_1574118985169/work/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())] ```

Is a different technique expected for loading? Or a particular flag to pass to signify it's a proto model?

**Comment by owos** [comment]
> `sp = spm.SentencePieceProcessor()`

@taku910  I think you added a `d` by mistake. It should be `SerializeToString` right?

**Comment by RRaphaell** [comment]
@taku910 
I am trying to initialize a [MarianTokenizer](https://huggingface.co/docs/transformers/en/model_doc/marian#transformers.MarianTokenizer), which requires a sentencepiece model file in .model or .spm format. I would like to generate this file from a HuggingFace tokenizer, specifically the BERT tokenizer.

I attempted to create an empty sentencepiece model and manually add token pieces to it in order to generate a tokenizer compatible with the MarianTokenizer. While this approach successfully creates a tokenizer, it splits the text differently compared to the BERT tokenizer.
For example, when tokenizing the word "hello", the manually created tokenizer splits it into "he" and "llo", whereas the BERT tokenizer keeps "hello" as a single token.
```target_tokenizer = spm.SentencePieceProcessor()
target_tokenizer_spm = sp_pb2_model.ModelProto()
target_tokenizer_spm.ParseFromString(target_tokenizer.serialized_model_proto())
for p, piece in ...
  new_p = sp_pb2_model.ModelProto().SentencePiece()
  new_p.piece = piece
  new_p.score = p.score
  new_p.type = p.type
  target_tokenizer_spm.pieces.append(new_p)
```

What is the simplest way to convert the BERT tokenizer to the required sentencepiece format that can be used to initialize the MarianTokenizer?

I haven't been able to find a solution elsewhere, so I'm hoping you might be able to provide some guidance. Thank you for your help!
