### ISSUE TITLE
Problem about mixed-language word

### ISSUE THREAD

**Issue by LuShengDong** [google/sentencepiece#126]
In Chinese, there are some words composed by an english letter and a chinese character. They should be recogized as one word during the tokenizing process. However, all the mixed-language words are splited when I use sentence piece to tokenize them. 

Is this a special feature in this tools that recognize the language before tokenizing? Can I disable this feature?

**Comment by taku910** [comment]
When training,  pass --split_by_unicode_script=false to spm_train which allows to extract pieces with Latin and Chinese characters.

One note is that SentencePiece is not a word segmenter. Segmented tokens are not always grammatical words. Because the number of vocabs are determined prior to the training, SentencePiece doesn't provide a functionality to strictly merge characters. For instance, any numerical expressions (1234, 4567) can be a word, but when we merge them into one token, the vocab size gets potentially infinite.

**Comment by LuShengDong** [comment]
Thanks, probelm solved!

BTW, although sentencepiece does not strictly merge characters, it still outperforms tranditional tokenizing method in chinese when dictionary can not cover all the vocabulary in some special area such as fashion and agriculture. By tuning the hyperparameter, which is the number of vocabs, I got pretty good results on tokenization task
