### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by ehsanasgari** [google/sentencepiece#204]
Hi there, thank you for the great work. I was wondering if you are willing to make this package available in conda or conda-forge as well? That would be great, because then it can be used in packages using conda recipes.

**Comment by zhangguanheng66** [comment]
As a downstream library of sp, I was wondering if there is any progress for this issue.
https://github.com/pytorch/text/issues/717

**Comment by setu4993** [comment]
+1, would love to see this on `conda-forge` to simplify using with conda environments. I have been trying to get it on `conda-forge`, but cannot figure out how to compile from source on MacOS X. (Works locally, but there's something different about it on conda because of which it fails.) Appreciate any and all help on it!
https://github.com/conda-forge/staged-recipes/pull/10580

**Comment by lufol** [comment]
Any updates on this?

**Comment by taku910** [comment]
Seems conda-forget package is available. Let me close this bug. Thank you.

https://anaconda.org/conda-forge/sentencepiece
