### ISSUE TITLE
Information about protobuf

### ISSUE THREAD

**Issue by emjotde** [google/sentencepiece#254]
Hi,
we will probably try to implement a version of SentencePiece that does not rely on protobuf. It's a really heavy dependency and it would be nice to be able to keep the our tool rather lightweight. 

I am trying to figure out quickly where protobuf is actually used. As far as I see it's the main model file itself. and it primary usage is model serialization, is this correct?

**Comment by emjotde** [comment]
Oh, wonderful. I will keep an eye open. Let me know if you want help.

**Comment by taku910** [comment]
Sorry for keeping you wait.

I've finally got rid of the dependency to (external) protobuf.  I first tried to use nanopb, but  turned out that using immutable protobuf with nanopb requires extra work and makes the code unsafe because of malloc/free operations.  So I decided to use protobuf-lite, which is a lightweight runtime of protobuf. 

Here's the high-level summary

- The minimum code for running protobuf-lite is copied to third_party/protobuf-lite. No need to install protobuf in advance.
- The builtin (copied) runtime is compiled and used by default.
- You can use the external protobuf with `cmake .. -DSPM_USE_BUILTIN_PROTOBUF=OFF`
- The runtime size is much smaller: full:2-3M, lite:200k-300k.
- Re-implemented the features depending on the full protobuf (e.g., reflection and text output).

Please let me know if you have any questions. I will update the document soon.

**Comment by taku910** [comment]
Updated the document.

Please feel free to reopen this issue if you find any problems.

**Comment by emjotde** [comment]
Great. Thank we will be very useful. Thanks a lot for your good work.

**Comment by Zuwei-Zhao** [comment]
Hi @taku910 , is the protobuf-lite in sentencepiece compatible with other version protobuf?

Besides your guidance above to set `SPM_USE_BUILTIN_PROTOBUF OFF`, how could I make sentencepiece project depend on external protobuf like the **protobuf in other folders or projects**? Thanks.
