### ISSUE TITLE
RuntimeError hard-coded path 

### ISSUE THREAD

**Issue by chagri** [google/sentencepiece#296]
import sentencepiece as spm

sp = spm.SentencePieceProcessor()
sp.Load(<some_file_path>)

  File "/Users/user/anaconda3/lib/python3.6/site-packages/sentencepiece.py", line 118, in Load
    return _sentencepiece.SentencePieceProcessor_Load(self, filename)
RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by taku910** [comment]
Seems this is not an error. This hard-coded path is embedded in the binary during the build time, and telling where the error happens. (73 lines in sentencepiece_processor.cc)

The RuntimeError is raised because an incorrect model file is passed to `Load` function. The model file should be generated with `spm_train` or `SentencePieceProcessor::Train` API.
