### ISSUE TITLE
Bad alloc with unigram version

### ISSUE THREAD

**Issue by valentinmace** [google/sentencepiece#308]
Hello, I have a `what():  std::bad_alloc
Aborted (core dumped)
`
 
I know you already answered this issue but I tried both --hard_vocab_limit=false and --seed_sentencepiece_size=10000000 and I still get the problem

My corpus has ~34 million lines, I have 500gb RAM (but currently I think only 70gb available)

The command I use looks like:
`spm_train --input=my_input --model_prefix=en_clean_unigram --vocab_size=32000 --character_coverage=1.0 --model_type=unigram --hard_vocab_limit=false --seed_sentencepiece_size=10000000
`

Thanks in advance for your time

**Update:**

I've used the following command, this time with --input_sentence_size and it works. However does that mean I only use 5 millions sentences of my corpus ? Wouldn't it be better to use the whole corpus ?

`spm_train --input=my_input --model_prefix=en_clean_unigram --vocab_size=32000 --character_coverage=1.0 --model_type=unigram --num_threads=40 --input_sentence_size=5000000 --shuffle_input_sentence=true`

**Comment by taku910** [comment]
Yes,  5M sentences are only used for training. In addition, spm_train randomly sample 5M sentences from the entire corpus to get rid of unexpected bias.

I think 5M sentences are enough to train reasonable model when the vocab size is small, e.g., 32k, since the spm_extract only 32k tokens from the corpus.  This setting would not change the model drastically even with small subsets as long as the training data is randomly sampled.
