### ISSUE TITLE
Normalizer converts some chars to sequences of periods

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [google/sentencepiece#329]
This happens with a unigram model. I can narrow it down to the `NormalizePrefix()` function: the character goes in, dots come out (https://github.com/google/sentencepiece/blob/master/src/normalizer.cc#L126)

- It happens with many characters, including some Chinese and Arabic
- It happens even if the problematic character is in the training data, and character coverage is 1.0: the char is not added to the vocab
- It happens with the python interface or the c++ binary

```
>>> y = sp.EncodeAsPieces('︰')  # \ufe30
>>> y
['\u2581', '.', '.']
>>> sp.DecodePieces(y)
'..'
```

**Comment by 1-800-BAD-CODE** [comment]
Seems to work fine if I use `--normalization_rule_name=identity`.

However, this might still be an issue because the default normalization can silently alter the semantics of the input text, as well as break reversibility.

**Comment by taku910** [comment]
This is an expected behavior as Unicode NFKC normalization.
By default,  sentencepiece normalizes the input with NFKC.

U+FE30 is vertical two dots (not colon), which are used in vertical writing system and semantically equivalent to double period (..). 

According to Unicode spec, U+FE30 can be decomposed to U+002E/U+002E (..)
https://www.compart.com/en/unicode/U+FE30

```
>>> import unicodedata
>>> print(unicodedata.normalize('NFKC', u'\uFE30'))
..
```

The conversion rule is in data/nmt_nfkc.tsv

```
% grep FE30 nmt_nfkc.tsv 
FE30    2E 2E   # ︰ => ..
```

It would be possible to remove this specific normalization

```
% grep -v FE30 nmt_nfkc.tsv > custom.tsv
% spm_train --normalization_rule_tsv=custom.tsv
```

**Comment by 1-800-BAD-CODE** [comment]
OK thanks, the reason it surprised me is that I did not expect default settings to modify the inputs. It seems obvious in hindsight, though.
