### ISSUE TITLE
Is the link to python module dead? 

### ISSUE THREAD

**Issue by leolcling** [google/sentencepiece#343]
The link to python module leads to a 404 not found page... Does anyone have the same issue?

**Comment by fozziethebeat** [comment]
Yes, this is temporarily disabled.  We're working on unifying the open source codebase and the Google internal codebase to simplify maintenance.  For a short period of time, a few features will be missing and/or broken.

**Comment by Bachstelze** [comment]
Is there a stable branch or a working tag?

**Comment by stefan-it** [comment]
Engineering-wise that's totally bad practice what's going on here: No working documentation, but at least `bazel` is working? Why are we forced to use `bazel` now?

Several nlp libraries rely on sentencepiece. It would be great if "internal merges" could be tested before merging it into the open-source `master` branch.

**Comment by fozziethebeat** [comment]
I agree this isn't the best engineering practice.  Our primary effort has been to make sure our code base inside and outside of Google are the same and can be maintained, with a stronger focus for keeping internal Google needs met.  

This situation came about because sentencepiece was not originally released in a way that could be maintained in conjunction with our internal version, and now we're handling the consequences of that.  Further, we (the Google internal maintainers) have shrinking amount of time to support this project.  The best I can say is that master will be broken for specific use cases until we can resolve all the issues in migrating to Bazel.  For a stable version, I recommend using the release in https://github.com/google/sentencepiece/releases/tag/v0.1.82

**Comment by taku910** [comment]
We've decided to rollback the recent bazel stuff and moved it to new bazel branch.
We will start the migration once bazel branch gets stable.

We will keep this issue opened just for the reference of bazel branch. Thank you.

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
