### ISSUE TITLE
[Q] Would you elaborate the differences of 4 corpus size parameters?

### ISSUE THREAD

**Issue by deasuke** [google/sentencepiece#35]
I have 50M sentences corpus to train. I'd like to know the difference of following parameters.
I set 50M, 10M, 5M, 50M respectively (x5 of default) and got crashed like issue#4 --
CHECK(!pieces.empty()) failed on serialize.
The vocab size I set was 32768.

```
   --input_sentence_size (maximum size of sentences the trainer loads)  type: int32  default: 10000000
   --mining_sentence_size (maximum size of sentences to make seed sentence piece)  type: int32  default: 2000000
   --seed_sentencepiece_size (the size of seed sentencepieces)  type: int32  default: 1000000
   --training_sentence_size (maximum size of sentences to train sentence pieces)  type: int32  default: 10000000
```

**Comment by taku910** [comment]
Sorry for the confusions.

--input_sentence_size: The number of lines spm_train first loads. Remaining lines are simply discarded.  Since spm_train loads entire corpus into memory, this size will depend on the memory size of the machine. It also affects training time.

--training_sentence_size: The number of lines to train BPE/unigram model.

--mining_sentence_size: The number of lines to generate seed pieces. spm_train extracts frequent substring from the corpus with suffix array, which requires O(10N) memory space.  This setting is valid when --model_type=unigram.  

--seed_sentencepiece_size:  The size of seed pieces. This setting is valid when --model_type=unigram.

In general, we can use the default values except for --input_sentence_size.  Training spm with more than 10M sentences requires tons of memory and CPU resources.
