### ISSUE TITLE
Explanation of encoding method

### ISSUE THREAD

**Issue by rmrao** [google/sentencepiece#406]
I'm trying to understand the code in [bpe_model.cc](https://github.com/google/sentencepiece/blob/master/src/bpe_model.cc). From explanations I've found on the internet, BPE encodes a string in a greedy fashion, replacing the longest possible subsequence first. However, your code seems to use a priority queue and recursive resegmentation? Does this implement a fundamentally different approach to encoding, or is this simply for speed? If you could point me to a paper that explains this, that would be great - it doesn't seem to be explained in the SentencePiece paper, unless I'm missing something.

**Comment by taku910** [comment]
The current implementation is BPE.  We use Priority queue for segmentation efficiency. Naive implementation requires O(N^2) cost, while priority queue can reduce it to O(N log N).

In each iteration of BPE, we first the most frequent pair of symbols and replace them to new one. Since almost all pairs will not change its frequency, we can manage them in priority queue.

**Comment by liyang85105** [comment]
same question, still very confused
