### ISSUE TITLE
Issue in installing.

### ISSUE THREAD

**Issue by tkhan3** [google/sentencepiece#452]
Python 3.7.3
OS: Redhat

I am getting following error message while installing:

I already tried installing wheel but getting message:
```
(tanveer) [ai_u@powcbds tanveer]$ pip install sentencepiece-0.1.85-cp38-cp38-manylinux1_i686.whl
ERROR: sentencepiece-0.1.85-cp38-cp38-manylinux1_i686.whl is not a supported wheel on this platform.
```

```
> Using cached sentencepiece-0.1.83.tar.gz (497 kB)
>   ERROR: Command errored out with exit status 1:
>    command: /power8nfs/home/ai_u/.conda/envs/tanveer/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6kz16kgn/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6kz16kgn/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6kz16kgn/sentencepiece/pip-egg-info
>        cwd: /tmp/pip-install-6kz16kgn/sentencepiece/
>   Complete output (7 lines):
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-6kz16kgn/sentencepiece/setup.py", line 29, in <module>
>       with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
>     File "/power8nfs/home/ai_u/.conda/envs/tanveer/lib/python3.7/codecs.py", line 904, in open
>       file = builtins.open(filename, mode, buffering)
>   FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
>   ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
```

**Comment by electricjoe-dev** [comment]
Same here. Jetson Xavier, Ubuntu 18.04, Jetpack 4.3

Haven't resolved it yet. I would love to hear the solution.

**Comment by alexjuda** [comment]
+1, macOS 10.15.2, Python 3.8.0

**Comment by tkhan3** [comment]
@electricjoe-dev seems there is some problem with their pip package. I was able to install sentencepiece via conda as:

`conda install -c powerai sentencepiece`

Hope it may help

**Comment by Digimonseeker** [comment]
same problem！

**Comment by Digimonseeker** [comment]
I just solved! Download this zip folder, put the PYTHON folder into your  SITE-PACKAGES under your environments, then rename the PYTHON folder with sentencepiece.

**Comment by electricjoe-dev** [comment]
Is there an attached zip folder? I don't see one. Now I'm quite anxious to try the fix :)

**Comment by Digimonseeker** [comment]
> Is there an attached zip folder? I don't see one. Now I'm quite anxious to try the fix :)
Download this folder above, i.e. "google/sentencepiece", then you can do the following steps.

**Comment by electricjoe-dev** [comment]
Thanks! I _think_ that got me a step further. I'm trying to run NeMo unit tests. Now it says 'cannot import name SentencePieceTrainer.

**Comment by black938** [comment]
+1, macOS 10.15.2, Python 3.8.0

**Comment by fakerbrother** [comment]
> I just solved! Download this zip folder, put the PYTHON folder into your SITE-PACKAGES under your environments, then rename the PYTHON folder with sentencepiece.

Yes，I have solved this problem in your way! :)

**Comment by eightypercentcoffee** [comment]
@Digimonseeker can you specify where to find the zip file

**Comment by dilutedh2o** [comment]
OS: alpine

I have the exact same problem, have been cracking my head over it all week.

Also doesn't work when you try to build from source.

Commands run:
```
pip install pyyaml setuphelpers
git clone https://github.com/google/sentencepiece.git
cd sentencepiece
mkdir build
cd build
cmake ..
make -j $(nproc)
make install
ldconfig -v
```

Output:
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/pkgconfig/sentencepiece.pc
-- Installing: /usr/local/lib/libsentencepiece.so.0.0.0
-- Installing: /usr/local/lib/libsentencepiece.so.0
-- Installing: /usr/local/lib/libsentencepiece.so
-- Installing: /usr/local/lib/libsentencepiece_train.so.0.0.0
-- Installing: /usr/local/lib/libsentencepiece_train.so.0
-- Set runtime path of "/usr/local/lib/libsentencepiece_train.so.0.0.0" to ""
-- Installing: /usr/local/lib/libsentencepiece_train.so
-- Installing: /usr/local/lib/libsentencepiece.a
-- Installing: /usr/local/lib/libsentencepiece_train.a
-- Installing: /usr/local/bin/spm_encode
-- Set runtime path of "/usr/local/bin/spm_encode" to ""
-- Installing: /usr/local/bin/spm_decode
-- Set runtime path of "/usr/local/bin/spm_decode" to ""
-- Installing: /usr/local/bin/spm_normalize
-- Set runtime path of "/usr/local/bin/spm_normalize" to ""
-- Installing: /usr/local/bin/spm_train
-- Set runtime path of "/usr/local/bin/spm_train" to ""
-- Installing: /usr/local/bin/spm_export_vocab
-- Set runtime path of "/usr/local/bin/spm_export_vocab" to ""
-- Installing: /usr/local/include/sentencepiece_trainer.h
-- Installing: /usr/local/include/sentencepiece_processor.h
```
And then just stops with error code 1 but no message :man_shrugging:

**Comment by Evpok** [comment]
I think there are several different issues here:

-@tkhan3, you are trying to install a Python 3.8 wheel with Python 3.7, it is normal that it fails. It is supposed to
- Installing from source (which pip does when it can't install from a wheel is [more complex](https://github.com/google/sentencepiece/tree/master/python#build-and-install-sentencepiece), in particular, you have to install the C++ library yourself before
- @alexjuda and @black938 are trying to install with Python 3.8, but from macosx [for which there are no wheel in the latest release](https://github.com/google/sentencepiece/releases/tag/v0.1.85), thus falling in the previous issue

@taku910 Could you maybe add a wheel release for cp38-macos? That would solve the problem in the short term. In the long term, would it be possible to make `setup.py` build the C++ library? That would solve the issue of source dist (users would still have to install the build deps, but that seems easier than requiring they build the whole lib themselves).

**Comment by taku910** [comment]
Can you still see the problem?  I would like to close it as we already support py 3.8

**Comment by alexjuda** [comment]
Re-checked today, now it works for me at Python 3.8.1, macOS 10.15.4 via a regular `pip install sentencepiece`. Thanks for fixing it!

**Comment by taku910** [comment]
Okay, let me close this bug. Feel free to reopen it if you find any problem.

**Comment by prateekg** [comment]
While trying to pip install sentencepiece:


Using legacy setup.py install for sentencepiece, since package 'wheel' is not installed.                                                                                Installing collected packages: sentencepiece                                                                                                                                Running setup.py install for sentencepiece ... error                                                                                                                    ERROR: Command errored out with exit status 1:                                                                                                                           command: 'c:\users\dell\appdata\local\programs\python\python35\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-_mok036o\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-_mok036o\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-op81ue5l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python35\Include\sentencepiece'                                                                                                                          cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\                                                                                          Complete output (15 lines):                                                                                                                                             running install                                                                                                                                                         running build                                                                                                                                                           running build_py                                                                                                                                                        creating build                                                                                                                                                          creating build\lib.win-amd64-3.5                                                                                                                                        copying sentencepiece.py -> build\lib.win-amd64-3.5                                                                                                                     running build_ext                                                                                                                                                       building '_sentencepiece' extension                                                                                                                                     creating build\temp.win-amd64-3.5                                                                                                                                       creating build\temp.win-amd64-3.5\Release                                                                                                                               C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\dell\appdata\local\programs\python\python35\include -Ic:\users\dell\appdata\local\programs\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsentencepiece_wrap.cxx /Fobuild\temp.win-amd64-3.5\Release\sentencepiece_wrap.obj /MT /I..\build\root\include                                                                                                     cl : Command line warning D9025 : overriding '/MD' with '/MT'                                                                                                           sentencepiece_wrap.cxx                                                                                                                                                  sentencepiece_wrap.cxx(2777): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory                                       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2                                                                                                                                                                          ----------------------------------------                                                                                                                            ERROR: Command errored out with exit status 1: 'c:\users\dell\appdata\local\programs\python\python35\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-_mok036o\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-_mok036o\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-op81ue5l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python35\Include\sentencepiece' Check the logs for full command output.   


""Suggest something to install it, it's a dependency I need to install for Transformers""

**Comment by Cather-learner** [comment]
> While trying to pip install sentencepiece:
> 
> Using legacy setup.py install for sentencepiece, since package 'wheel' is not installed. Installing collected packages: sentencepiece Running setup.py install for sentencepiece ... error ERROR: Command errored out with exit status 1: command: 'c:\users\dell\appdata\local\programs\python\python35\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\setup.py'"'"'; **file**='"'"'C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-op81ue5l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python35\Include\sentencepiece' cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\ Complete output (15 lines): running install running build running build_py creating build creating build\lib.win-amd64-3.5 copying sentencepiece.py -> build\lib.win-amd64-3.5 running build_ext building '_sentencepiece' extension creating build\temp.win-amd64-3.5 creating build\temp.win-amd64-3.5\Release C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\dell\appdata\local\programs\python\python35\include -Ic:\users\dell\appdata\local\programs\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsentencepiece_wrap.cxx /Fobuild\temp.win-amd64-3.5\Release\sentencepiece_wrap.obj /MT /I..\build\root\include cl : Command line warning D9025 : overriding '/MD' with '/MT' sentencepiece_wrap.cxx sentencepiece_wrap.cxx(2777): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe' failed with exit status 2 ---------------------------------------- ERROR: Command errored out with exit status 1: 'c:\users\dell\appdata\local\programs\python\python35\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\setup.py'"'"'; **file**='"'"'C:\Users\Dell\AppData\Local\Temp\pip-install-_mok036o\sentencepiece\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-op81ue5l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python35\Include\sentencepiece' Check the logs for full command output.
> 
> ""Suggest something to install it, it's a dependency I need to install for Transformers""

Have you solved the problem? I met the same problem as you

**Comment by Adhundi7** [comment]
> @electricjoe-dev seems there is some problem with their pip package. I was able to install sentencepiece via conda as:
> 
> `conda install -c powerai sentencepiece`
> 
> Hope it may help

This was helpful, I was able to install! Thank you!

**Comment by saketkattu** [comment]
> > @electricjoe-dev seems there is some problem with their pip package. I was able to install sentencepiece via conda as:
> > `conda install -c powerai sentencepiece`
> > Hope it may help
> 
> This was helpful, I was able to install! Thank you!


was not able to install using conda or pip 


(pt) C:\Users\KATTUBOINA>conda install -c powerai sentencepiece
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sentencepiece

Current channels:

  - https://conda.anaconda.org/powerai/win-64
  - https://conda.anaconda.org/powerai/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by PFython** [comment]
> I just solved! Download this zip folder, put the PYTHON folder into your SITE-PACKAGES under your environments, then rename the PYTHON folder with sentencepiece.

Worked for me too and save me a whole load of pain, thanks very much!
