### ISSUE TITLE
Likelihood in the loss computation

### ISSUE THREAD

**Issue by Ryou0634** [google/sentencepiece#462]
Hello, I'm trying to understand how sentencepiece works in detail, and have a question for the loss computation part.

https://github.com/google/sentencepiece/blob/0f6db9477090688f3f8368fa9598b332b7d3c6dc/src/unigram_model_trainer.cc#L305-L307

In this part, it seems that the likelihood is computed by counting the token frequency in the viterbi path. However, I feel that it is more natural to use the expected token frequency over all possible paths, as computed in the EM algorithm or described in your paper. Why does the loss computation deviate from the true likelihood of the unigram LM, or am I misunderstanding something?

Thank you.

**Comment by taku910** [comment]
Yes, as you pointed out, we would like to use expected frequency here. However, it should be too resource consuming.

The 'exact' computation is like

```
for `piece`in current vocab.
    ll = current loss
    remove `piece` from vocab
    run EM w/o `piece`
    ll2 = loss w/o `piece`
    delta[piece] = ll2 - ll
end

remove piece with the smallest delta.
````

As we can see, running EM for all piece is too resource consuming. So, here we just approximate the delta as follows.
1) Use Viterbi path (hard-EM) instead 
2) instead of removing the `piece`, replace `piece` with the alternative segmentation of `piece`.  For instance, the piece `hello` is segmented as `he` and `llo` as the second best segmentation, we assume that all `hello` in the corpus is segmented as `he` and `llo` when removing `hello`.

**Comment by Ryou0634** [comment]
Thank you for your clarification!
What I was not sure was the approximation by hard-EM, but now it is clear to me.
