### ISSUE TITLE
Force tokenizer to ignore special characters

### ISSUE THREAD

**Issue by zaidalyafeai** [google/sentencepiece#493]
I want to train `sentencepiece` but the text has some special characters that should be considered as part of words i.e the tokenizer shouldn't add space/prerpocess them. 

For instance, if I want to tokenize the statement 
`stmt = I +am +good`
The plus sign shouldn't be considered as a punctuation i.e the output might be 
`tokenized = ["I", "+am", "+good"] `

Any idea how to do that ?

**Comment by taku910** [comment]
It would be difficult to introduce such constraint if the sequence after "+" is an open-class word. In general, we it is hard to introduce a constraint to concatenate characters because vocabulary size is pre-defined.   For example, the rule to concatenate any numbers [0-9] may yield infinite vocabulary in the end.

If the sequence after + is closed class, we can just enumerate all possible sequences and define them as user defined symbols.
