### ISSUE TITLE
spm_encode an entire file using Python API

### ISSUE THREAD

**Issue by jerrybai1995** [google/sentencepiece#508]
Hi,

I'm looking for a way to replicate the exact same effect of 
```
spm_encode --model=<model_file> --output_format=piece < input > output
```
(which encodes the entire `input` file to produce `output` file) in the Python wrapper. However, `sp.encode` seems to support only string input only. Is there anyway that I can do this without using a for loop to go through every line in `input`?

Thanks for the help!

**Comment by taku910** [comment]
You might want to try Python's file io.

```
import sentencepiece as spm

sp = spm.SentencePieceProcessor(model_file='test_model.model')
with open('input.txt', 'r') as rf, open('output.txt', 'w') as wf:
    for line in rf:
        wf.write(' '.join(sp.encode(line, out_type=str)))
````

**Comment by hassani24** [comment]
Hello.  I know this issue is closed but I was having issues using your suggestion @taku910 - I did a diff between the output of spm_encode and the code above and realized that everything was being put into 1 long string.  I added a wf.write("\n") to the loop and now it works perfectly.  The output of the python code is identical to the output of the binary

sp = spm.SentencePieceProcessor(model_file='test_model.model')
with open('input.txt', 'r') as rf, open('output.txt', 'w') as wf:
    for line in rf:
        wf.write(' '.join(sp.encode(line, out_type=str)))
        wf.write("\n")
