### ISSUE TITLE
How to SampleEncode with a specific random state?

### ISSUE THREAD

**Issue by CZWin32768** [google/sentencepiece#521]
Hi Taku,

I am currently trying to incorporate subword regularization into my data generation pipeline. 

Due to the limited time and storage, I want to apply subword regularization online. I am wondering whether the spm model always generates the same sequences in different runs, because I want to compare different models with the same input sequences that are generated by spm.

It seems that providing a random state to each encode operation can ensure that the generated sequences only depends on the random state.

Could you please provide me some suggestions on how to achieve this?

Thanks,
Zewen

**Comment by taku910** [comment]
Currently, we use a device specific generator to set the seed.

https://github.com/google/sentencepiece/blob/master/src/util.cc#L165

You can get the behavior predictable by setting fixed seed value here. However, you have to carefully manage the order of sentences, since the random sequence depends only on this seed.

At this moment, we will not have a plan to add a method to specify random variable, but you can emulate it with n-best output.

SentencePiece has n-best output mode. You can get multiple segmentations with this mode.  For example, you can choose the sentence with hash(sentence) from the nbest.  The selection only depends on the input sentence.

**Comment by CZWin32768** [comment]
Thanks!
