### ISSUE TITLE
What is the meaning of the second column of the .vocab file (using BPE)?

### ISSUE THREAD

**Issue by dskoo** [google/sentencepiece#555]
I trained tokenizer using 'BPE mode'. After training I got the .vocab file below.

But I can't understand the second column meaning.

I know that line number is id of tokens... but what's the meaning of second column?

um      -0
num     -1
▁<      -2
▁해     -3
▁해외   -4

**Comment by taku910** [comment]
The second column is the score of the piece (bigger is the better).   This score is used in unigram mode. In BPE, we put a dummy score. Since we do not know the maximum score in BPE, it starts from 0 for the sake of convenience. Anyway, in BPE, second column has no meaning, but the order of the piece is important.

**Comment by tianxin1860** [comment]
> The second column is the score of the piece (bigger is the better). This score is used in unigram mode. In BPE, we put a dummy score. Since we do not know the maximum score in BPE, it starts from 0 for the sake of convenience. Anyway, in BPE, second column has no meaning, but the order of the piece is important.

Could you explain how the order influence the tokenize? thanks
