### ISSUE TITLE
Feature request: remove symbols 

### ISSUE THREAD

**Issue by danielinux7** [google/sentencepiece#577]
Hello,
Is it possible to add this option: 
**--remove_symbols_file=remove_symbols.txt**
Where remove_symbols.txt is:
\<symbol1\>
\<symbol2\>

**Comment by taku910** [comment]
Could you elaborate your requests?   Does it mean that we do not include the specified symbols during the training?  Or do we remove the symbols from the trained model file?

In addition, it would be great if you share the reason why these options are required.

**Comment by danielinux7** [comment]
I meant to remove the symbols from the trained model file.
i.e if I have these symbols in models's vocab:
> ?
!
.
?!.
▁?

I want ?!. and ▁? to be removed.

**Comment by taku910** [comment]
We do not officially support the features that makes a destructive operations on the trained model at this moment, since there are bunch of usages and hard to generalize them. In addition, we would not like to recommend such mutable operations,  since the principle of sentencepiece is to perform non-destructive operations.

However, it is possible to manually modify the trained model. The model file is encoded in protobuf. Here's the example to add new vocab to the model. Please try it at your own risk basis.
https://github.com/google/sentencepiece/blob/master/python/add_new_vocab.ipynb

**Comment by danielinux7** [comment]
For reference, I tried the following working code to remove unwanted symbols.
> for p in pieces:
   m.pieces.remove(p)
