### ISSUE TITLE
Unicode characters assigned to "inherited" script are not handled properly

### ISSUE THREAD

**Issue by ddaspit** [google/sentencepiece#731]
According to the [Unicode Standard, Annex #24, version 13.0.0](http://www.unicode.org/reports/tr24/tr24-31.html#Script_Values), "inherited" is a special script property that is assigned to characters that should inherit their script value from the preceding base character.  When SentencePiece determines the script of a character for the purposes of applying the `split_by_unicode_script` option, it does not assign an "inherited" script character the script of the preceding character. It treats "inherited" as a separate script. This can causes issues for scripts that commonly use "inherited" characters.

**Comment by taku910** [comment]
It would be helpful if you could provide specific examples. (current and expected behavior)

**Comment by mmartin9684-sil** [comment]
Some of the characters that are affected by this issue include the following 'inherited' Arabic characters:
- Arabic Fatha
- Arabic Sukun
- Arabic Kasra
- Arabic Damma
- Arabic Shadda
- Arabic Fathatan
- Arabic Kasratan
- Arabic Dammatan
When a SP vocab is built from text that includes these characters, each of these characters is generally identified as a separate subword token.  Occasionally a pair of these characters will be combined into a subword, but these characters will never form a subword with regular Arabic characters (e.g., Alef, Lam, Yeh) because they are considered different scripts.

Attached are two SP vocab files that demonstrate how these inherited characters are separated from the Arabic characters rather than being incorporated into subwords with the Arabic characters:

[src-sp.vocab.txt](https://github.com/google/sentencepiece/files/8365195/src-sp.vocab.txt)
[trg-sp.vocab.txt](https://github.com/google/sentencepiece/files/8365197/trg-sp.vocab.txt)

Also attached are several log files showing the setting used to generate the SP vocab files.  The first log is from an unsuccessful run that uses a typical vocab size (6000 subwords), and demonstrates the unusually small vocab size that has to be used to create the SP vocab file for Arabic text: 
[preprocess.fail.log](https://github.com/google/sentencepiece/files/8365202/preprocess.fail.log)
The second log file is from a successful run, and documents the configuration settings being used.
[preprocess.success.log](https://github.com/google/sentencepiece/files/8365204/preprocess.success.log)

**Comment by mmartin9684-sil** [comment]
Another issue is that both the nmt_nfkc.tsv and nmt_nfkc_cf.tsv files continue to map the zero width non-joiner (ZWNJ) character (u+200C) to <space>.  The earlier mappings of ZWJ (u+200D) to <space> were removed, but the mapping for ZWNJ has not yet been removed.  Both of these are Inherited characters, and need to inherit the script of the preceding character in order to being identified as a subword boundary.

**Comment by mmartin9684-sil** [comment]
In addition, the nmt_nkfc_cf.tsv file maps Arabic characters in the FE70..FEFF range to alternate Arabic characters in the 062x..064x range.  These mappings were removed from the nmt_nkfc.tsv file earlier, but haven't yet been removed from the nmt_nkfc_cf.tsv file.

When building a multilingual SP vocab including Arabic text and using case folding (for the other languages), these mappings will result in improper content in the tokenized text.
