### ISSUE TITLE
Possibility for NFKD or Strip Accents support?

### ISSUE THREAD

**Issue by Ashvio** [google/sentencepiece#751]
Hey all,

Just wondering if there's a possibility for adding other normalizers like NFKD as an option. If not, could someone lead me in a direction to find TSVs for that kind of normalizer? Thanks!

**Comment by taku910** [comment]
All Unicode normalizations start with NF(K)D. The current NFKC mapping is built from the NFD sequence, so it is relatively easy to have the NFKD mapping.

https://github.com/google/sentencepiece/blob/master/src/builder.cc#L312

**Comment by taku910** [comment]
Just added a mapping table (TSV) for NFKD. This is an optional mapping, and not used via ``--normalization_rule_name``
Please specify the file as ``--normalization_rule_name_tsv=nfkd.tsv`` 

https://github.com/google/sentencepiece/blob/master/data/nfkd.tsv

We don't support the "strip accent" mapping beucase it's hard to define a universal strip-accent mapping, and their definitons are totally application dependent.  Please make the mapping by removing the accent code points from the nfkd.tsv.

**Comment by Ashvio** [comment]
Thank you! Appreciate all the work youve done for this project.

**Comment by taku910** [comment]
Hmm, it seems that it simply removes combination marks. It is technically possible, but I personally don't like it as it doesn't universally work.   For example, Japanese か and が (か＋” ) are different character, and removing the mark will completely change the meaning of the word. e.g. がらす (glass) -> からす (crow).   Because MacOS filesystem uses NFKD, we have a lot of troubles in Japanese filename string matches. e.g. か matches が

**Comment by Ashvio** [comment]
It's not for every use case, but there are situations where needing to remove accents is important (eg, people using accents on latin characters to obfuscate their text
