### ISSUE TITLE
Why is only one sentence per line allowed in input files?

### ISSUE THREAD

**Issue by molokanov50** [google/sentencepiece#755]
Hello team,

From the viewpoint of many NMT users, is seems more reasonable to translate **several** sentences at once in order to conserve more sense, more thematics from neighboring sentences as well as cohesion and semantic coherence of the text. Of course, memory-related limitations of neural networks are situated much higher and constitute about 200 to 500 tokens, so it seems possible to provide a text consisting of ~10 sentences as an input. However, for most of popular NMT frameworks, SentencePiece preprocessing of an input text and SentencePiece model dictionaries are like a standard. So why is only one sentence per line allowed in input files for SentencePiece preprocessing? There probably is no clarification of this fact in literature. Is it a limitation of SentencePiece? How can it be argumented? It is any sacrifice for the sake of gaining some benefits?

**Comment by taku910** [comment]
There may be a problem with the current document, but there is no limit to the input unit of sentencepiece. SentencePiece doesn't assume that input is a grammatical sentence. We can feed any "text', including words, phrases, multiple sentences and so on.  ``spm_train`` (C++ CLI tool) uses "\n" as a delimiter of these texts for the sake of convenience and consistency with other Unix commands. It would be better to say one-text-per-line format rather than one-sentence-per-line. 

Python module can feed multiiple "texts" with "\n". 

```
import sentencepiece as spm

texts=['hello \n world. foo \n bar', 'this is a test.\n']
spm.SentencePieceTrainer.train(input=iter(texts), model_prefix='m',...)
```
