### ISSUE TITLE
Letters are split

### ISSUE THREAD

**Issue by wizardk** [google/sentencepiece#839]
I trained a model on my corpus. But when I use that trained model to encoding some sentences in my corpus, I found two letters split apart. One is that ŀ(0x0140) is split into l and ·, and the other is that ŉ(0x0149) is split into ʼ and n.

@taku910 What is the reason for this? Thanks.

**Comment by taku910** [comment]
By default, input texts are normalized with NFKC. NFKC normalizes "U+149" into two characters "U+2BC U+6E", so it is expected behavior.  To suppress this behavior you can try either

1.  completely disable the normalization with `--normalization_rule_name=identity`.
2.  removes the line ```149     2BC 6E  # ŉ => ʼn``` from 1```data/nmt_nfkc.tsv``` and train the model with ```--normalization_rule_tsv=data/nmt_nfkc.tsv```

**Comment by wizardk** [comment]
@taku910 Thanks.
Based on method 1, this parameter needs to be added during calling spm_train, but not during calling spm_encode, right?

**Comment by taku910** [comment]
Yes, both 1&2 must be applied in the training phase (spm_trian)
