### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by yurivict** [google/sentencepiece#977]
[log](https://freebsd.org/~yuri/py-sentencepiece-0.2.0-tests.log)

Version: 0.2.0
Python-3.9
clang-16
FreeBSD 14.0

**Comment by taku910** [comment]
Since we do not know how this log was generated, we cannot reproduce or address it.
It would be helpful if you could share the log using standard methods.

Here is the standard way to run python test

```
% wget https://github.com/google/sentencepiece/releases/download/v0.2.0/sentencepiece-0.2.0.tar.gz
% tar zxfv sentencepiece-0.2.0.tar.gz
% cd sentencepiece-0.2.0
% python setup.py test
````

Furthermore, since FreeBSD is not included in the CI test targets, it would be difficult to reproduce this error in the first place.

**Comment by yurivict** [comment]
```python setup.py test``` runs tests successfully.

We used to run ```pytest``` and it was failing.

Thanks for your help.
